### ISSUE TITLE
Test new bigoli firmware

### ISSUE THREAD

**Issue by chsahit** [RoboJackets/roboracing-firmware#2] opened 2017-09-25 17:03 UTC
We need to reasonably version control the mbed firmware and also start testing it on hardware

- Test a P controller on steering
- Tune PD control on motor output
- Test I/O between MBED firmware and ROS node on the NUC

**Comment by btdubs** [comment] 2018-09-30 21:58
The code is done minus some cleanup after competition. It also now has ethernet connection instead of serial.

**Comment by btdubs** [comment] 2018-10-21 00:35
Added a note to self here, I think the Bigoli firmware has a similar problem to Sedani, where we don't check for a terminating character. This should be fixed before merging Ethernet (bigoli-firmware) to master

**Comment by jspall0327** [comment] 2018-12-15 19:57
Will the note ^^ for this be handled by the new wrapper? Aka close this issue.

**Comment by jspall0327** [comment] 2018-12-16 18:33
I agree, that's what we should do. I just think issue #15 handles the comment about terminating character and the original intention of the issue was resolved with bigoli comp code merged earlier during this semester. Just think the issue is outdated.

**Comment by btdubs** [comment] 2019-09-09 21:58
Closing this because RIP Bigoli. That pasta will always have a special place in our hearts.

**Closed by btdubs** 2019-09-09 21:58 UTC
